version: "3"


services:
  db:
    container_name: mongo
    image: mongo
    command: mongod --port 27017 --bind_ip_all
    volumes:
      - db-data:/data/db
    ports: 
      - "27017:27017"
  app:
    container_name: parking-service
    build: .
    depends_on:
      - db
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
volumes:
  db-data:
